# Generated by Django 4.0.4 on 2022-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
