# Generated by Django 4.0.4 on 2022-10-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_remove_apartment_floor_apartment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
