# Generated by Django 4.0.4 on 2022-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_remove_apartment_floor_apartment_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='2DImages'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='3DImages'),
        ),
    ]
