# Generated by Django 4.0.4 on 2022-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_apartment_image_alter_apartment_image_2d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
