# Generated by Django 4.0.4 on 2023-03-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_apartment_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCSVData',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apartment.floor',),
        ),
    ]
