# Generated by Django 4.0.4 on 2022-10-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendEmail', '0002_email_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='success',
        ),
    ]
