# Generated by Django 4.0.4 on 2022-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Advertising'),
        ),
    ]
